/*
USER ACTION TYPES
 */
export const LOAD_USER = 'LOAD_USER';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAILURE = 'LOAD_USER_FAILURE';

export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

export const EDIT_USER = 'EDIT_USER';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAILURE = 'EDIT_USER_FAILURE';

export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';

/*
APP ACTION TYPES
 */
export const GET_CURRENT_LOCALE = 'GET_CURRENT_LOCALE';
export const CHANGE_LOCALE = 'CHANGE_LOCALE';

/*
AUTH ACTION TYPES
 */
export const LOG_USER_IN = 'LOG_USER_IN';
export const LOG_USER_IN_SUCCESS = 'LOG_USER_IN_SUCCESS';
export const LOG_USER_IN_FAILURE = 'LOG_USER_IN_FAILURE';

export const LOG_USER_OUT = 'LOG_USER_OUT';
export const LOG_USER_OUT_FAILURE = 'LOG_USER_OUT_FAILURE';
export const LOG_USER_OUT_SUCCESS = 'LOG_USER_OUT_SUCCESS';

export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';

export const SET_SESSION =  'SET_SESSION';
export const SET_MESSAGE =  'SET_MESSAGE';

/*
CHAT ACTION TYPES
 */
export const LOAD_MESSAGE = 'LOAD_MESSAGE';
export const LOAD_MESSAGE_SUCCESS = 'LOAD_MESSAGE_SUCCESS';
export const LOAD_MESSAGE_FAILURE = 'LOAD_MESSAGE_FAILURE';

export const LOAD_ONLINE_USER = 'LOAD_ONLINE_USER';
export const LOAD_ONLINE_USER_SUCCESS = 'LOAD_ONLINE_USER_SUCCESS';
export const LOAD_ONLINE_USER_FAILURE = 'LOAD_ONLINE_USER_FAILURE';

export const ADD_MESSAGE = 'ADD_MESSAGE';

export const ADD_USER = 'ADD_USER';
export const REMOVE_USER = 'REMOVE_USER';